# Generated by Django 4.2.20 on 2025-04-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_group_projectcategories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                default=(
                    "pbkdf2_sha256$600000$nI24sQ6SMrCktse"
                    "q8GsQEN$3g3MpxyFn93g3H7ID5xW+y7VriQhhpoCRoprZq4x4Wk="
                ),
                max_length=128,
                verbose_name="password",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
