# Generated by Django 4.2.20 on 2025-04-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_supervisorofstudentgroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='supervisor', to='app.projectcategories'),
        ),
    ]
