# Generated by Django 4.2.20 on 2025-04-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_supervisor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorstudentcomments',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_comments', to='app.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supervisorstudentcomments',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_comments', to='app.student'),
        ),
        migrations.AlterField(
            model_name='supervisorstudentcomments',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_comments', to='app.supervisor'),
        ),
    ]
