# Generated by Django 4.2.20 on 2025-05-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopeDocumentEvaluationCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_statement",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "validity_of_he_proposed_solution",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "motivation_behind_tools_and_technologies",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "modules",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "task_management",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "related_system_analysis",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "document_format",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "plagiarism_report",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="supervisorofstudentgroup",
            name="Scope_document_evaluation_form",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scope_document_evaluation_form",
                to="app.scopedocumentevaluationcriteria",
            ),
        ),
    ]
