# Generated by Django 4.2.20 on 2025-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_scopedocumentevaluationcriteria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeemember",
            name="group",
            field=models.ManyToManyField(
                blank=True,
                related_name="committee_member",
                to="app.supervisorofstudentgroup",
            ),
        ),
    ]
