# Generated by Django 4.2.20 on 2025-05-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_committeemember_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeMemberPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="committeemember",
            name="group",
        ),
        migrations.AddField(
            model_name="committeemember",
            name="panel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committee_member",
                to="app.committeememberpanel",
            ),
            preserve_default=False,
        ),
    ]
