# Generated by Django 4.2.20 on 2025-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_committeememberpanel_remove_committeemember_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeememberpanel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
