# Generated by Django 4.2.20 on 2025-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_committeememberpanel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeememberpanel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
