# Generated by Django 4.2.20 on 2025-05-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_committeememberpanel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="panel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_panel",
                to="app.committeememberpanel",
            ),
            preserve_default=False,
        ),
    ]
