# Generated by Django 4.2.20 on 2025-05-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_project_panel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="panel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="app.committeememberpanel",
            ),
        ),
    ]
