# Generated by Django 4.2.20 on 2025-05-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_alter_project_panel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supervisorofstudentgroup",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="app.project",
            ),
        ),
    ]
