# Generated by Django 4.2.20 on 2025-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_supervisorofstudentgroup_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopedocumentevaluationcriteria',
            name='plagiarism_report',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
