# Generated by Django 4.2.20 on 2025-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_student_semester_srstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='srstemplate',
            name='semester',
            field=models.CharField(blank=True, choices=[('semester_6', 'Semester 6'), ('semester_7', 'Semester 7'), ('semester_8', 'Semester 8')], max_length=100, null=True),
        ),
    ]
