# Generated by Django 4.2.20 on 2025-05-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_document_document_type_delete_srsdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeMemberTemplates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("semester_6", "Semester 6"),
                            ("semester_7", "Semester 7"),
                            ("semester_8", "Semester 8"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("srs_template", "SRS Template"),
                            ("sdd_template", "SDD Template"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("uploaded_file", models.FileField(upload_to="templates/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_templates",
                        to="app.committeemember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SRSEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_1_marks", models.IntegerField(blank=True, null=True)),
                ("student_2_marks", models.IntegerField(blank=True, null=True)),
                (
                    "regularity",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "srs_are_frs_mapped_to_the_problem",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "srs_are_nfr_mapped_to_the_problem",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "is_srs_storyboarding",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "according_to_requirement",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "is_srs_template_followed",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "is_write_up_correct",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "student_participation",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("marginal", "Marginal"),
                            ("adequate", "Adequate"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SRSEvaluationSupervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regularity", models.IntegerField(default=0)),
                ("fr_mapping", models.IntegerField(default=0)),
                ("nfr_mapping", models.IntegerField(default=0)),
                ("requirement_analysis", models.IntegerField(default=0)),
                ("mock_defined", models.IntegerField(default=0)),
                ("template_followed", models.IntegerField(default=0)),
                ("technical_writeup", models.IntegerField(default=0)),
                ("seminar_participation", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SRSTemplate",
        ),
        migrations.AddField(
            model_name="supervisorofstudentgroup",
            name="srs_evaluation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_of_students",
                to="app.srsevaluation",
            ),
        ),
    ]
