# Generated by Django 4.2.20 on 2025-05-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_document_document_type_delete_srsdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMemberTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('semester_6', 'Semester 6'), ('semester_7', 'Semester 7'), ('semester_8', 'Semester 8')], max_length=100)),
                ('template_type', models.CharField(choices=[('srs_template', 'SRS Template'), ('sdd_template', 'SDD Template')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(upload_to='templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_templates', to='app.committeemember')),
            ],
        ),
        migrations.CreateModel(
            name='SRSEvaluationSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regularity_percent', models.IntegerField(choices=[(15, '10%-20% (Marginal)'), (40, '30%-50% (Adequate)'), (70, '60%-80% (Good)'), (95, '90%-100% (Excellent)')], default=0)),
                ('fr_mapping_percent', models.IntegerField(choices=[(15, '10%-20% (Marginal)'), (40, '30%-50% (Adequate)'), (70, '60%-80% (Good)'), (95, '90%-100% (Excellent)')], default=0)),
                ('nfr_mapping_percent', models.IntegerField(choices=[(15, '10%-20% (Marginal)'), (40, '30%-50% (Adequate)'), (70, '60%-80% (Good)'), (95, '90%-100% (Excellent)')], default=0)),
                ('requirement_analysis_percent', models.IntegerField(choices=[(15, '10%-20% (Marginal)'), (40, '30%-50% (Adequate)'), (70, '60%-80% (Good)'), (95, '90%-100% (Excellent)')], default=0)),
                ('mock_defined_percent', models.IntegerField(choices=[(15, '10%-20% (Marginal)'), (40, '30%-50% (Adequate)'), (70, '60%-80% (Good)'), (95, '90%-100% (Excellent)')], default=0)),
                ('template_followed_percent', models.IntegerField(choices=[(15, '10%-20% (Marginal)'), (40, '30%-50% (Adequate)'), (70, '60%-80% (Good)'), (95, '90%-100% (Excellent)')], default=0)),
                ('technical_writeup_percent', models.IntegerField(choices=[(15, '10%-20% (Marginal)'), (40, '30%-50% (Adequate)'), (70, '60%-80% (Good)'), (95, '90%-100% (Excellent)')], default=0)),
                ('seminar_participation_percent', models.IntegerField(choices=[(15, '10%-20% (Marginal)'), (40, '30%-50% (Adequate)'), (70, '60%-80% (Good)'), (95, '90%-100% (Excellent)')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SRSTemplate',
        ),
    ]
