# Generated by Django 4.2.20 on 2025-05-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_committeemembertemplates_srsevaluation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SRSEvaluationSupervisor',
        ),
    ]
