# Generated by Django 4.2.20 on 2025-05-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_evaluation3supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation3CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_completion', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('software_testing', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('qa_ability', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('proper_attire', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_template_followed', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('is_writeup_correct', models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evaluation3supervisor',
            name='is_template_followed',
            field=models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='evaluation3supervisor',
            name='is_writeup_correct',
            field=models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='evaluation3supervisor',
            name='module_completion',
            field=models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='evaluation3supervisor',
            name='regularity',
            field=models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='evaluation3supervisor',
            name='software_testing',
            field=models.CharField(choices=[('pending', 'Pending'), ('marginal', 'Marginal'), ('adequate', 'Adequate'), ('good', 'Good'), ('excellent', 'Excellent')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='supervisorofstudentgroup',
            name='evaluation3_committee_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_students', to='app.evaluation3committeemember'),
        ),
    ]
