# Generated by Django 4.2.20 on 2025-05-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_remove_chatroom_group_name_remove_chatroom_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluation3supervisor",
            name="project_domain_knowledge",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("marginal", "Marginal"),
                    ("adequate", "Adequate"),
                    ("good", "Good"),
                    ("excellent", "Excellent"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
