# Generated by Django 4.2.20 on 2025-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0035_evaluation3supervisor_project_domain_knowledge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemembertemplates",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("srs_template", "SRS Template"),
                    ("sdd_template", "SDD Template"),
                    ("final_report_template", "Final Report Template"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("scope_document", "Scope Document"),
                    ("srs_document", "SRS Document"),
                    ("sdd_document", "SDD Document"),
                    ("final_report_document", "Final Report Document"),
                ],
                max_length=50,
            ),
        ),
    ]
