# Generated by Django 4.2.20 on 2025-05-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_supervisor_academic_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='app.supervisorofstudentgroup'),
        ),
    ]
