# Generated by Django 4.2.20 on 2025-05-25 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0038_alter_chatroom_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewIdeaProject",
        ),
    ]
