# Generated by Django 4.2.21 on 2025-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0041_alter_document_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemembertemplates",
            name="uploaded_file",
            field=models.FileField(upload_to="doc_templates/"),
        ),
    ]
