# Generated by Django 4.2.20 on 2025-06-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0043_alter_committeemembertemplates_template_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Templates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("semester_6", "Semester 6"),
                            ("semester_7", "Semester 7"),
                            ("semester_8", "Semester 8"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("scope_documents_template", "Scope Document Template"),
                            ("srs_template", "SRS Template"),
                            ("sdd_template", "SDD Template"),
                            ("final_report_template", "Final Report Template"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("uploaded_file", models.FileField(upload_to="doc_templates/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CommitteeMemberTemplates",
        ),
    ]
