# Generated by Django 4.2.20 on 2025-06-15 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0044_templates_delete_committeemembertemplates"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Templates",
            new_name="Template",
        ),
    ]
