from django.urls import path
from .views import (
    NewIdeaProjectAPIVIEW,
    GroupRequestView,
    StudentLoginView,
    StudentsListView,
    StudentProfileView,
    ChangePasswordView,
    ProjectCategoriesView,
    ProjectAPIVIEW,
    StudentProposalListAPIView,
    SupervisorStudentCommentsAPIView,
    SendSupervisorRequestAPIView,
    SupervisorResponseAPIView,
    SupervisorLoginAPIView,
    CommitteeMemberLoginAPIView,
    SupervisorProfileView,
    GroupComments,
    CommitteeMemberProfileView,
    ListSuperisorAPIView,
    DocumentUploadAPIView,
    GroupDetailView,
    SendSupervisorRequestDetailAPIView,
    ScopeDocumentEvaluationCriteriaView,
    PanelAPIView,
    CommitteeMemberPanelDetailAPIView,
    ProjectDetailAPiView,
    SupervisorStudentDetailAPIView,
    CommitteeMemberTemplatesAPIView,
    SRSEvaluationSupervisorView,
    SRSEvaluationCommitteeMemberView,
    SDDEvaluationCommitteeMemberView,
    SDDEvaluationSupervisorView,
)


urlpatterns = [
    path("student/login/", StudentLoginView.as_view(), name="student-login"),
    path("student/profile/", StudentProfileView.as_view(), name="student-profile"),
    path(
        "supervisor/login/", SupervisorLoginAPIView.as_view(), name="supervisor-login"
    ),
    path(
        "supervisor/profile/",
        SupervisorProfileView.as_view(),
        name="supervisor-profile",
    ),
    path(
        "committee_member/login/",
        CommitteeMemberLoginAPIView.as_view(),
        name="committee-member-login",
    ),
    path(
        "committee_member/profile/",
        CommitteeMemberProfileView.as_view(),
        name="committee-member-profile",
    ),
    path("change_password/", ChangePasswordView.as_view(), name="change_password"),
    path("listofstudents/", StudentsListView.as_view(), name="listofstudents"),
    path(
        "project/categories/",
        ProjectCategoriesView.as_view(),
        name="project-categories",
    ),
    path("groupmate/request/", GroupRequestView.as_view(), name="groupmate-request"),
    path("group/<int:pk>/", GroupDetailView.as_view(), name="group-detail"),
    path(
        "groupmate/<int:group>/comments/",
        GroupComments.as_view(),
        name="groupmate-comments",
    ),
    path("projects/list/", ProjectAPIVIEW.as_view(), name="projects-list"),
    path(
        "projects/new_idea/",
        NewIdeaProjectAPIVIEW.as_view(),
        name="projects-new-idea",
    ),
    path(
        "student/proposal/list/",
        StudentProposalListAPIView.as_view(),
        name="student-proposal-list",
    ),
    path(
        "supervisor/list/",
        ListSuperisorAPIView.as_view(),
        name="supervisor-list",
    ),
    path(
        "supervisor/student/comments/",
        SupervisorStudentCommentsAPIView.as_view(),
        name="supervisor-student-comments",
    ),
    path(
        "supervisor/student/request/",
        SendSupervisorRequestAPIView.as_view(),
        name="supervisor-student-request",
    ),
    path(
        "supervisor-student/<int:pk>/",
        SendSupervisorRequestDetailAPIView.as_view(),
        name="supervisor-student-request",
    ),
    path(
        "supervisor/student/response/",
        SupervisorResponseAPIView.as_view(),
        name="supervisor-student-response",
    ),
    path(
        "proposal-document/<str:document_type>/",
        DocumentUploadAPIView.as_view(),
        name="document-upload",
    ),
    path(
        "scope_document_evaluation_criteria/<int:pk>/",
        ScopeDocumentEvaluationCriteriaView.as_view(),
        name="scope-document-evaluation-criteria",
    ),
    path(
        "srs-evaluation-supervisor/<int:pk>/",
        SRSEvaluationSupervisorView.as_view(),
        name="srs-evaluation-supervisor",
    ),
    path(
        "srs-evaluation-committee-member/<int:pk>/",
        SRSEvaluationCommitteeMemberView.as_view(),
        name="srs-evaluation-committee-member",
    ),
    path(
        "sdd-evaluation-committee-member/<int:pk>/",
        SDDEvaluationCommitteeMemberView.as_view(),
        name="sdd-evaluation-committee-member",
    ),
    path(
        "sdd-evaluation-supervisor/<int:pk>/",
        SDDEvaluationSupervisorView.as_view(),
        name="sdd-evaluation-supervisor",
    ),
    path(
        "panel/<int:pk>/",
        PanelAPIView.as_view(),
        name="panel-detail",
    ),
    path(
        "committee-member/<int:pk>/",
        CommitteeMemberPanelDetailAPIView.as_view(),
        name="committee-member-detail",
    ),
    path(
        "project/<int:pk>/",
        ProjectDetailAPiView.as_view(),
        name="project-detail",
    ),
    path(
        "supervisor-student/<int:pk>/",
        SupervisorStudentDetailAPIView.as_view(),
        name="supervisor-student-detail",
    ),
    path(
        "srs_template/<str:template_type>/",
        CommitteeMemberTemplatesAPIView.as_view(),
        name="srs-template",
    ),
]
